### ISSUE TITLE
Folder Permissions

### ISSUE THREAD

**Issue by tazzarkin** [Offerel/roundcube_pictures#1]
What folder permissions do I give?

(For example, who is owner and who is group.  Right now, I have root and root.)

I am using RoundCube with ISPConfig on Ubuntu.

**Comment by Offerel** [comment]
I'm not sure to what for folder your questions belongs. But all folder should be accessible at least by the webserver user. If i remember correctly, Ubuntu uses www-data as the user and www-data as the group. The plugin folder itself should be at least readable for this user and the gallery and it's subfolders must also be writeable, if you want to use move/write/copy functions.

I would strongly recommend to not use root right for such things, that is highly dangerous.
